/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.danross.toptask;

public final class R {
    public static final class array {
        public static final int categories=0x7f050001;
        public static final int priorities=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int add_icon=0x7f020000;
        public static final int app_icon=0x7f020001;
        public static final int blue_icon=0x7f020002;
        public static final int calendar_icon=0x7f020003;
        public static final int clock_icon=0x7f020004;
        public static final int delete_icon=0x7f020005;
        public static final int edit_icon=0x7f020006;
        public static final int gray_icon=0x7f020007;
        public static final int green_icon=0x7f020008;
        public static final int home_icon=0x7f020009;
        public static final int orange_icon=0x7f02000a;
        public static final int pink_icon=0x7f02000b;
    }
    public static final class id {
        public static final int body=0x7f060008;
        public static final int category_spinner=0x7f060001;
        public static final int confirm=0x7f060009;
        public static final int deletebutton=0x7f060011;
        public static final int description=0x7f06000c;
        public static final int editbutton=0x7f060010;
        public static final int end_spinner=0x7f060005;
        public static final int enddate=0x7f060006;
        public static final int enddatebutton=0x7f060007;
        public static final int img=0x7f06000a;
        public static final int insertbutton=0x7f06000d;
        public static final int mainbutton=0x7f06000f;
        public static final int name=0x7f06000b;
        public static final int start_spinner=0x7f060002;
        public static final int startdate=0x7f060003;
        public static final int startdatebutton=0x7f060004;
        public static final int taskdescription=0x7f060015;
        public static final int taskimg=0x7f060013;
        public static final int tasklist=0x7f06000e;
        public static final int taskname=0x7f060012;
        public static final int taskpriority=0x7f060014;
        public static final int title=0x7f060000;
    }
    public static final class layout {
        public static final int edit_task=0x7f030000;
        public static final int listview=0x7f030001;
        public static final int main=0x7f030002;
        public static final int view_task=0x7f030003;
    }
    public static final class string {
        public static final int about=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int author=0x7f040002;
        public static final int body=0x7f040008;
        public static final int category_prompt=0x7f04000d;
        public static final int confirm=0x7f04000b;
        public static final int date=0x7f040010;
        public static final int edit_task=0x7f04000c;
        public static final int end_prio=0x7f04000a;
        public static final int end_priority_prompt=0x7f04000f;
        public static final int no_tasks=0x7f040003;
        public static final int start_prio=0x7f040009;
        public static final int start_priority_prompt=0x7f04000e;
        public static final int task_delete=0x7f040005;
        public static final int task_edit=0x7f040006;
        public static final int task_insert=0x7f040004;
        public static final int time=0x7f040011;
        public static final int title=0x7f040007;
    }
}
